// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// largest_na_block
RObject largest_na_block(const NumericMatrix M, SEXP max_perim, int num_results);
RcppExport SEXP _ajtools_largest_na_block(SEXP MSEXP, SEXP max_perimSEXP, SEXP num_resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_perim(max_perimSEXP);
    Rcpp::traits::input_parameter< int >::type num_results(num_resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(largest_na_block(M, max_perim, num_results));
    return rcpp_result_gen;
END_RCPP
}
// sort_blocks_diagonally
RObject sort_blocks_diagonally(NumericMatrix M);
RcppExport SEXP _ajtools_sort_blocks_diagonally(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sort_blocks_diagonally(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ajtools_largest_na_block", (DL_FUNC) &_ajtools_largest_na_block, 3},
    {"_ajtools_sort_blocks_diagonally", (DL_FUNC) &_ajtools_sort_blocks_diagonally, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ajtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
