# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

largest_na_block <- function(M, max_perim = NULL, num_results = 1L) {
    .Call(`_ajtools_largest_na_block`, M, max_perim, num_results)
}

sort_blocks_diagonally <- function(M) {
    .Call(`_ajtools_sort_blocks_diagonally`, M)
}

